spring:
  application:
    name: 19-relationships
  datasource:
    url: jdbc:h2:mem:relationships;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        generate_statistics: true
  sql:
    init:
      mode: always

logging:
  level:
    org.hibernate.SQL: debug
