spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sb4docs
    username: sb4
    password: sb4
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
